In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

ModuleNotFoundError: No module named 'plotly'

In [3]:
standing_df = pd.read_csv('data/results/league_standings.csv')
standing_df.head()

,season,league,team,points,wins,draws,losses,goals_for,goals_against,goal_diff,played,position
0,2008/2009,Belgium Jupiler League,RSC Anderlecht,77,24,5,5,75,30,45,34,1
1,2008/2009,Belgium Jupiler League,Standard de Liège,77,24,5,5,66,26,40,34,2
2,2008/2009,Belgium Jupiler League,KAA Gent,59,17,8,9,67,42,25,34,3
3,2008/2009,Belgium Jupiler League,Club Brugge KV,59,18,5,11,59,50,9,34,4
4,2008/2009,Belgium Jupiler League,SV Zulte-Waregem,55,16,7,11,55,36,19,34,5

In [4]:
home_adv_df = pd.read_csv('data/results/home_advantage.csv')
home_adv_df.head()

,league,season,avg_home_goals,avg_away_goals,home_advantage,win_percent,draw_percent,loss_percent
0,Netherlands Eredivisie,2010/2011,1.944444,1.281046,0.663399,0.522876,0.232026,0.245098
1,Switzerland Super League,2009/2010,1.994444,1.333333,0.661111,0.550000,0.161111,0.288889
2,Belgium Jupiler League,2011/2012,1.754167,1.125000,0.629167,0.495833,0.270833,0.233333
3,England Premier League,2009/2010,1.697368,1.073684,0.623684,0.507895,0.252632,0.239474
4,Poland Ekstraklasa,2010/2011,1.504167,0.904167,0.600000,0.516667,0.250000,0.233333

In [6]:
running_pts_df = pd.read_csv('data/results/running_points_total.csv')
running_pts_df.head()

           team     season                 date  rolling_5_game_points
0  Ruch Chorzów  2008/2009  2008-08-10 00:00:00                      1
1  Ruch Chorzów  2008/2009  2008-08-16 00:00:00                      4
2  Ruch Chorzów  2008/2009  2008-08-22 00:00:00                      7
3  Ruch Chorzów  2008/2009  2008-08-30 00:00:00                      7
4  Ruch Chorzów  2008/2009  2008-09-12 00:00:00                     10

In [8]:
ssn_over_ssn_df = pd.read_csv('data/results/season_over_season.csv')
ssn_over_ssn_df.head()

,season,league,team,points,prev_season_points,points_change
0,2010/2011,Germany 1. Bundesliga,1. FC Kaiserslautern,46,NaN,NaN
1,2011/2012,Germany 1. Bundesliga,1. FC Kaiserslautern,23,46.0,-23.0
2,2008/2009,Germany 1. Bundesliga,1. FC Köln,39,NaN,NaN
3,2009/2010,Germany 1. Bundesliga,1. FC Köln,38,39.0,-1.0
4,2010/2011,Germany 1. Bundesliga,1. FC Köln,44,38.0,6.0